import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Playfair_Display, Inter } from "next/font/google";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  title: "Aria Voss — Painter & Fine Artist",
  description:
    "Explore the original oil paintings of Aria Voss — landscapes, portraits, and abstract works that capture light, emotion, and the beauty of the natural world.",
  keywords: ["Aria Voss", "painter", "oil paintings", "fine art", "gallery", "landscape", "portrait", "abstract"],
  openGraph: {
    title: "Aria Voss — Painter & Fine Artist",
    description:
      "Explore the original oil paintings of Aria Voss — landscapes, portraits, and abstract works.",
    type: "website",
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    <html lang="en" className={`${playfair.variable} ${inter.variable}`}>
      <body>{children}</body>
    </html>
  );
}
